### ISSUE TITLE
CSS Inheritence

### ISSUE THREAD

**Issue by cyouh95** [jmvogie/prj-rev-bwfs-dasmoto#3]
Alternatively, you could specify `font-family: Helvetica;` for the entire `body` element. Then, all the children element would automatically inherit this property without you needing to specify it for each:

```css
body {
  font-family: Helvetica;
}
```
https://github.com/jmvogie/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/css/style.css
